#!/usr/bin/env bash

CC=clang

files=()
opts=()
libs=()
obj_files=()
target=""
no_rm_pp=true

expect_target=false
compile_only=false
all_object_file=true

for arg in "$@"; do
  if [ "$expect_target" = true ]; then
    target="$arg"
    expect_target=false
    continue
  fi

  case "$arg" in
    -E)
      no_rm_pp=false
      ;;
    -gcc)
      CC=gcc
      ;;
    -pico)
      opts+=("-D__PICO__")
      ;;
    -o)
      #opts+=("$arg")
      expect_target=true
      ;;
    -c)
      compile_only=true
      #opts+=("$arg")
      ;;
    -l*)
      libs+=("$arg")
      ;;
    -*)
      opts+=("$arg")
      ;;
    *.o) 
      obj_files+=("$arg")
      ;;
    *.nc)
      files+=("$arg")
      all_object_file=false
      ;;
    *)
      files+=("$arg")
      all_object_file=false
      ;;
  esac
done

#base="${1}"
base="${files[0]%.nc}"

ncc ${opts[@]} ${files[0]}

transpile_ok=$?

if [ "$all_object_file" == true ]
then
    $CC ${opts[@]} -o ${target} ${files[@]} -L/opt/homebrew/opt/openssl/lib -L/opt/homebrew/opt/boehmgc/lib -L/opt/homebrew/opt/zstd/lib -I/opt/homebrew/opt/openssl/include -L/opt/homebrew/opt/ncurses/lib ${obj_files[@]} ${libs[@]}
elif test $transpile_ok = 0
then
    if test $compile_only = true
    then
        if test -z "$target"
        then
            target=${base}.o
        fi
        
        #echo $CC -c ${opts[@]} -o ${target} ${base}.c 2> ${base}.c.error 
        if $CC -L/opt/homebrew/opt/openssl/lib -L/opt/homebrew/opt/boehmgc/lib -L/opt/homebrew/opt/zstd/lib -I/opt/homebrew/opt/openssl/include -L/opt/homebrew/opt/ncurses/lib -c ${opts[@]} -o ${target} ${base}.c ${libs[@]} 2> ${base}.c.error
        then
            rm ${base}.c.error
            if test $no_rm_pp = true
            then
                rm ${base}.nc.i
            fi
        else
            cat ${base}.c.error | grep error; exit 3
        fi
    else 
        if test -z "$target"
        then
            target=${base}
        fi
        
        #echo $CC ${opts[@]} -o ${target} ${base}.c 2> ${base}.c.error 
        if $CC -L/opt/homebrew/opt/openssl/lib -L/opt/homebrew/opt/boehmgc/lib -L/opt/homebrew/opt/zstd/lib -I/opt/homebrew/opt/openssl/include ${opts[@]} -L/opt/homebrew/opt/ncurses/lib -o ${target} ${base}.c ${obj_files[@]} ${libs[@]} 2> ${base}.c.error
        then
            rm ${base}.c.error
            if test $no_rm_pp = true
            then
                rm ${base}.nc.i
            fi
        else
            cat ${base}.c.error | grep error; exit 3
        fi
    fi
fi    
